---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
    app: goapp
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.realtime: semver:~0.0
    #fluxcd.io/locked: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: accountservice
        image: registry-443.service.consul/linux/app
        ports:
        - containerPort: 6767
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice-svc
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
  - protocol: TCP
    port: 6767
