---
jobs:

- name: compile-go-app
  public: true
  serial: true
  plan:
  - get: dev-branch
    trigger: true
  - task: build-application
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      inputs:
      - name: dev-branch
        path: go/src/github.com/ed201971/godaddy/
      outputs:
      - name: image
      run:
        path: /bin/sh
        args:
          - -c
          - |
              env
              export ROOTDIR=$PWD
              cd go/src/github.com/ed201971/godaddy/
              ./devops/build-context.sh
  - put: docker-image
    params: 
      build: image 
      tag_file: dev-branch/.git/ref
      tag_prefix: dev-
      labels:
        commit: dev-branch/.git/ref

- name: master-release
  public: true
  serial: true
  plan:
  - get: master-branch
  - get: docker-image
    params: 
      tag: master-branch/.git/ref
      save: true
  - get: version
    params: {bump: patch}
  - put: docker-image
    params: 
      load: docker-image
      additional_tags: version/number
  - put: version
    params: {file: version/version} 

resources:

- name: master-branch
  type: git
  source:
    uri: https://github.com/ed201971/godaddy.git
    branch: master

- name: dev-branch
  type: git
  source:
    uri: https://github.com/ed201971/godaddy.git
    branch: dev
    ignore_paths:
    - devops/concourse.yml

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/ed201971/godaddy.git 
    username: ((dockerhub_login))
    password: ((dockerhub_password))
    branch: master 
    file: version
    initial_version: 0.0.0

- name: docker-image
  type: docker-image
  source:
    username: ((docker_login)) 
    password: ((docker_password))
    repository: registry-443.service.consul/linux/app
    ca_certs: 
    - domain: registry-443.service.consul 
      cert: ((ca_cert))
