---
jobs:

- name: build-go-app
  public: true
  serial: true
  plan:
  - get: godaddy
    trigger: true
  - get: version
    params: {bump: minor}
  - task: get-dockerfile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}

      inputs:
      - name: godaddy
        path: go/src/github.com/ed201971/godaddy/

      run:
        path: /bin/sh
        args:
          - -c
          - |
            GOPATH=$PWD/go
            go get github.com/smartystreets/goconvey/convey
            cd go/src/github.com/ed201971/godaddy/
            go get ./...
            go test ./...
            ./devops/copyall.sh

  - put: docker-image
    params: 
      build: godaddy/devops
      tag_file: godaddy/.git/ref
      tag_prefix: splain
  - put: version
    params: {file: version/version} 

resources:
- name: godaddy
  type: git
  source:
    # private_key: ((ssh_key)) 
    uri: https://github.com/ed201971/godaddy.git 

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/ed201971/godaddy.git 
    branch: version
    file: version
    initial_version: 0.0.0

- name: docker-image
  type: docker-image
  source:
    username: ((docker_login)) 
    password: ((docker_password))
    repository: registry-443.service.consul/linux/app
    ca_certs: 
    - domain: registry-443.service.consul 
      cert: ((ca_cert))
