---
jobs:

- name: build-go-app-master
  public: true
  serial: true
  plan:
  - get: godaddy-master
    trigger: true
  - get: docker-image
    params: 
      tag: 0.0.4
      save: true
  - get: version
    params: {bump: patch}
  - task: get-dockerfile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      inputs:
      - name: docker-image
      run:
        path: /bin/sh
        args:
          - -c
          - |
            ls -la
  - put: docker-image
    params: 
      # build: godaddy/devops
      # load: 
      additional_tags: version/number
  - put: version
    params: {file: version/version} 

- name: build-go-app-dev
  public: true
  serial: true
  plan:
  - get: godaddy-dev
    trigger: true
  - task: get-dockerfile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: golang}
      inputs:
      - name: godaddy-dev
        path: go/src/github.com/ed201971/godaddy/
      run:
        path: /bin/sh
        args:
          - -c
          - |
            GOPATH=$PWD/go
            go get github.com/smartystreets/goconvey/convey
            cd go/src/github.com/ed201971/godaddy/
            go get ./...
            go test ./...
            ./devops/copyall.sh
  - put: docker-image
    params: 
      build: godaddy/devops
      tag_file: godaddy/.git/ref
      tag_prefix: splain

resources:
- name: godaddy-master
  type: git
  source:
    uri: https://github.com/ed201971/godaddy.git
    branch: master

- name: godaddy-dev
  type: git
  source:
    uri: https://github.com/ed201971/godaddy.git
    branch: dev

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/ed201971/godaddy.git 
    username: ed201971
    password: P0rka_26
    branch: master 
    file: version
    initial_version: 0.0.0

- name: docker-image
  type: docker-image
  source:
    username: ((docker_login)) 
    password: ((docker_password))
    repository: registry-443.service.consul/linux/app
    ca_certs: 
    - domain: registry-443.service.consul 
      cert: ((ca_cert))
