---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: godaddy-dev
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: godaddy-dev
  chart:
    git: git@github.com:ed201971/godaddy
    path: devops/godaddy-chart
    ref: dev 
  values:
    image:
      repository: registry-443.service.consul/linux/app
      tag: latest
