---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: godaddy-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: godaddy-dev
  chart:
    git: git@github.com:ed201971/godaddy
    path: devops/godaddy-chart
    ref: dev
  values:
    image:
      repository: registry-443.service.consul/linux/app
      tag: dev-b7ada34a272fa1f3dda7fe35aff2e372668b87ff
