---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: godaddy-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.0
spec:
  releaseName: godaddy-prod
  chart:
    git: git@github.com:ed201971/godaddy
    path: devops/godaddy-chart
    ref: master 
  values:
    image:
      repository: registry-443.service.consul/linux/app
      tag: 0.0.24
