language: go
go: 
    1.15.2

services:
 - docker

before_script:
- nvm install v10.15.0

script:
 - go test ./... 
 - ./devops/copyall.sh
# - docker build -t ed201971/godaddy devops/.

deploy:
  skip_cleanup: true
  provider: script
  script: bash devops/deploy.sh
  on:
    branch: master 
