---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  labels:
    app: goapp
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: accountservice
        image: ed201971/godaddy:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 6767
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice-svc
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
   - protocol: TCP
     port: 6767
